// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobiControlFirma.Infrastructure.Persistence;

#nullable disable

namespace MobiControlFirma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827234459_VistaEntregasCompletas")]
    partial class VistaEntregasCompletas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Canal", b =>
                {
                    b.Property<int>("CanalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CanalId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CanalId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Canales", (string)null);
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<int>("DispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispositivoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("CostoEquipo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("EstadoActualId")
                        .HasColumnType("int");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ICCID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IMEI")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobiControlDeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("varchar(30)");

                    b.HasKey("DispositivoId");

                    b.HasIndex("EstadoActualId");

                    b.HasIndex("IMEI")
                        .IsUnique()
                        .HasFilter("[IMEI] IS NOT NULL");

                    b.HasIndex("MobiControlDeviceId")
                        .IsUnique();

                    b.ToTable("Dispositivos", (string)null);
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Distrito", b =>
                {
                    b.Property<int>("DistritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistritoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DistritoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Distritos", (string)null);
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.DocumentoPdf", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoId"));

                    b.Property<int>("EntregaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("HashSHA256")
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("firmaentregadispositivo.pdf");

                    b.Property<string>("NombreContenedor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("documentos-pdf");

                    b.Property<string>("RutaBlob")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("TamanoBytes")
                        .HasColumnType("int");

                    b.Property<string>("UrlBlob")
                        .HasColumnType("varchar(1000)");

                    b.HasKey("DocumentoId");

                    b.HasIndex("EntregaId")
                        .IsUnique();

                    b.ToTable("DocumentosPDF", (string)null);
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CanalId")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("DistritoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("CanalId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("DistritoId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.EntregaDispositivo", b =>
                {
                    b.Property<int>("EntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntregaId"));

                    b.Property<int?>("CanalId")
                        .HasColumnType("int");

                    b.Property<string>("CiudadFirma")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Cali");

                    b.Property<string>("ClaveIdempotencia")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("CostoEquipo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<int?>("DistritoId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<Guid>("EntregaUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Entregables")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoProceso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("FIRMADO");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("FechaEntregaProgramada")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaFirma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ICCID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IPOrigen")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("NombreAsociadoFirmante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("EntregaId");

                    b.HasIndex("CanalId");

                    b.HasIndex("ClaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("UQ_EntregasDispositivo_Idempotencia")
                        .HasFilter("[ClaveIdempotencia] IS NOT NULL");

                    b.HasIndex("DispositivoId")
                        .HasDatabaseName("IX_EntregasDispositivo_Dispositivo");

                    b.HasIndex("DistritoId");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("IX_EntregasDispositivo_Empleado");

                    b.HasIndex("EntregaUid")
                        .IsUnique();

                    b.HasIndex("EstadoId");

                    b.HasIndex("EstadoProceso")
                        .HasDatabaseName("IX_EntregasDispositivo_EstadoProceso");

                    b.HasIndex("FechaFirma")
                        .HasDatabaseName("IX_EntregasDispositivo_Fecha");

                    b.ToTable("EntregasDispositivo", null, t =>
                        {
                            t.HasCheckConstraint("CK_EntregasDispositivo_EstadoProceso", "[EstadoProceso] IN ('FIRMADO','SINCRONIZADO','ERROR_SINCRONIZACION')");
                        });
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.EstadoDispositivo", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosDispositivo", (string)null);
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaId"));

                    b.Property<int>("EntregaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCaptura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FormatoImagen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("image/png");

                    b.Property<byte[]>("HashSHA256")
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("NombreContenedor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("firmas");

                    b.Property<string>("RutaBlob")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("TamanoBytes")
                        .HasColumnType("int");

                    b.Property<string>("UrlBlob")
                        .HasColumnType("varchar(1000)");

                    b.HasKey("FirmaId");

                    b.HasIndex("EntregaId")
                        .IsUnique();

                    b.ToTable("Firmas", (string)null);
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.IntegracionConfiguracion", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfiguracionId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("ApiKeyCifrada")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ClientIdCifrado")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ClientSecretCifrado")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PRODUCCION");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ParametrosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordCifrado")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoAutenticacion")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<byte[]>("UsuarioCifrado")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ConfiguracionId");

                    b.HasIndex("Proveedor", "Entorno")
                        .IsUnique()
                        .HasDatabaseName("UQ_IntegracionesConfig_Proveedor_Entorno");

                    b.ToTable("IntegracionesConfiguracion", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegracionesConfiguracion_ParametrosJson", "[ParametrosAdicionales] IS NULL OR ISJSON([ParametrosAdicionales]) = 1");

                            t.HasCheckConstraint("CK_IntegracionesConfiguracion_Proveedor", "[Proveedor] IN ('MOBICONTROL','INFOBIP','GUPSHUP')");

                            t.HasCheckConstraint("CK_IntegracionesConfiguracion_TipoAutenticacion", "[TipoAutenticacion] IN ('OAUTH_PASSWORD','API_KEY','BASIC')");
                        });
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.IntegracionSincronizacion", b =>
                {
                    b.Property<int>("SincronizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SincronizacionId"));

                    b.Property<int?>("CodigoRespuestaHttp")
                        .HasColumnType("int");

                    b.Property<int>("EntregaId")
                        .HasColumnType("int");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEjecucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("SincronizacionId");

                    b.HasIndex("EntregaId")
                        .HasDatabaseName("IX_IntegracionesSync_Entrega");

                    b.HasIndex("Proveedor")
                        .HasDatabaseName("IX_IntegracionesSync_Proveedor");

                    b.ToTable("IntegracionesSincronizaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegracionesSincronizaciones_Proveedor", "[Proveedor] IN ('MOBICONTROL','INFOBIP','GUPSHUP')");
                        });
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Dispositivo", b =>
                {
                    b.HasOne("MobiControlFirma.Domain.Entities.EstadoDispositivo", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("EstadoActualId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EstadoActual");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.DocumentoPdf", b =>
                {
                    b.HasOne("MobiControlFirma.Domain.Entities.EntregaDispositivo", "Entrega")
                        .WithOne("DocumentoPdf")
                        .HasForeignKey("MobiControlFirma.Domain.Entities.DocumentoPdf", "EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("MobiControlFirma.Domain.Entities.Canal", "Canal")
                        .WithMany()
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MobiControlFirma.Domain.Entities.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Canal");

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.EntregaDispositivo", b =>
                {
                    b.HasOne("MobiControlFirma.Domain.Entities.Canal", "Canal")
                        .WithMany()
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MobiControlFirma.Domain.Entities.Dispositivo", "Dispositivo")
                        .WithMany("Entregas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobiControlFirma.Domain.Entities.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MobiControlFirma.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Entregas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobiControlFirma.Domain.Entities.EstadoDispositivo", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Canal");

                    b.Navigation("Dispositivo");

                    b.Navigation("Distrito");

                    b.Navigation("Empleado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Firma", b =>
                {
                    b.HasOne("MobiControlFirma.Domain.Entities.EntregaDispositivo", "Entrega")
                        .WithOne("Firma")
                        .HasForeignKey("MobiControlFirma.Domain.Entities.Firma", "EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.IntegracionSincronizacion", b =>
                {
                    b.HasOne("MobiControlFirma.Domain.Entities.EntregaDispositivo", "Entrega")
                        .WithMany("Sincronizaciones")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Dispositivo", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("MobiControlFirma.Domain.Entities.EntregaDispositivo", b =>
                {
                    b.Navigation("DocumentoPdf");

                    b.Navigation("Firma");

                    b.Navigation("Sincronizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
